### PR TITLE
Added nth weekday per month - ex 2nd Monday

### PR DESCRIPTION
**Pull request by rmenner**
Created new RecurringFrequenceType to allow a format like "Every 3rd Thursday each month"

### CODE REVIEW

**Review by t1k3 — COMMENTED** [review]
This is a good idea, I like it.
Can you write tests, or do you need help?

**Comment by rmenner** [comment]
I will probably need help. Never written a test before. Unfortunately there is a bug.

**Comment by t1k3** [comment]
Okay, no problem. I will help you.

**Comment by t1k3** [comment]
The tests in `feature/nthweekday` branch: https://github.com/t1k3/laravel-calendar-event/tree/feature/nthweekday

I found a bug in your code, when I wrote tests, but I fixed it.
```php
// Console\Commands\GenerateCalendarEvent.php
// Models\CalendarEvent.php

case RecurringFrequenceType::NTHWEEKDAY:
    $diff = $templateCalendarEvent->start_date->diffInMonths($endOfRecurring);
    $nextMonth = $templateCalendarEvent->start_date->addMonths($diff);
    $dateNext = $nextMonth->nthOfMonth($nextMonth->weekOfMonth, $templateCalendarEvent->start_date->format('w'));
    break;
```

I used this docker image for testing: https://github.com/callan/docker-phpunit-php7
```bash
$ docker run -it --rm -v $PWD/laravel-calendar-event:/app epcallan/php7-testing-phpunit:7.2-phpunit5 bash
  $ cd app
  $ composer install
  $ phpunit # ./vendor/bin/phpunit
```

**Comment by t1k3** [comment]
I will migrate to Carbon 2, because 1 is deprecated.

**Pull request closed without merging**
